---
title: "First Knit"
author: "Mya orozco rodriguez"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  My highschool that I attended is named Highland High School and yes I did graduate, infact I graduated a year early. In my opinion english class is much more eaiser than math, math is way too confusing for me. During high school I would like to believe biology was the subject I did my absolute best in.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  My computer at home is a window 11, its a bit slow but it gets things done. If i would rate myslef it would be a 5, im not the best with this whole computer stuff but I can figure it out. My interent works well, it could be better but atleast it works even though sometimes it stops working out of nowhere.
   



## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I perfer just to be called my name, im used to it. I dont think I have any nicknames so I just stick to my name.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to be able to achieve my dream job which it is to be a business accountant. As for college subjects I think the greatest one for me would be Accounting 201. I would like to atleast get a bachelor’s degree, I dont exactly know my plan after college.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  The farthest I've ever gone is to mexico and it was wonderful I would love to go back soon. I would love to vist italy or toyko, its my dream places to explore. I have never been in the military before, but if I ever got drafed, I would like to go into the air force branch. I have an uncle who served and tells me all the stories about his time there, of course it was difficult and harmful but it was worth it help.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I've never taken Math 115 and im taking Math 116 right now. I actually did not know about it being an requirement for transfer institutions, I need to attain no lower than a B in stats for my future plans. My plan is to complete these two years of community college and transfer to UCLA as a business student to continue my path towards becoming an accountant.






  




